set_property(GLOBAL PROPERTY GLOBAL_DEPENDS_DEBUG_MODE 1)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)
set(CMAKE_DISABLE_SOURCE_CHANGES  ON)

set(CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL "Release" "")
set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO "Release" "")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include(GNUInstallDirs)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

#We will be using Qt
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)